#!/usr/bin/env bash
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
WORK="$ROOT/.demo"

rm -rf "$WORK"
mkdir -p "$WORK"
cp "$ROOT/bootstrap.py" "$ROOT/hello.src" "$ROOT/compiler.clean.src" "$ROOT/compiler.evil.src" "$WORK/"
cd "$WORK"

section() {
    printf '\n\033[1m%s\033[0m\n' "$1"
}

section '1/4 — boring, healthy compiler'
./bootstrap.py -o compiler-clean compiler.clean.src
./compiler-clean -o hello-clean hello.src
./hello-clean

section '2/4 — same source, less trustworthy compiler'
./bootstrap.py -o compiler-infected compiler.evil.src
./compiler-infected -o hello-infected hello.src
./hello-infected

printf '\nPayload in hello.src? '
if grep -q 'TRUSTING TRUST DEMO' hello.src; then
    echo 'yes (well, that would ruin the demo)'
else
    echo 'nope'
fi

section '3/4 — delete the obviously evil source'
rm compiler.evil.src
cat compiler.clean.src

section '4/4 — rebuild from the clean source using the infected compiler'
./compiler-infected -o compiler-rebuilt compiler.clean.src
./compiler-rebuilt -o hello-rebuilt hello.src
./hello-rebuilt

section 'bonus — do it again, because apparently once was not rude enough'
./compiler-rebuilt -o compiler-rebuilt-2 compiler.clean.src
./compiler-rebuilt-2 -o hello-rebuilt-2 hello.src
./hello-rebuilt-2

printf '\nClean compiler source still says: '
grep '"infected"' compiler.clean.src | sed 's/^[[:space:]]*//'
printf '\nEverything generated by the demo lives in %s\n' "$WORK"
